# Generated by Django 2.2.28 on 2023-11-17 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='race',
            new_name='couleur',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='type',
            new_name='marque',
        ),
        migrations.AddField(
            model_name='character',
            name='modele',
            field=models.CharField(default='Inconnu', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='pilote',
            field=models.CharField(default=datetime.datetime(2023, 11, 17, 15, 31, 19, 328134, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
